//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        monitoring_output_port_lookup_cpu_regs_defines.v
//
//  Module:
//        monitoring_output_port_lookup_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


`define  REG_RW0_BITS				31:0
`define  REG_RW0_WIDTH				32
`define  REG_RW0_DEFAULT				32'h0
`define  REG_RW0_ADDR				32'h0

`define  REG_RW1_BITS				31:0
`define  REG_RW1_WIDTH				32
`define  REG_RW1_DEFAULT				32'h0
`define  REG_RW1_ADDR				32'h4

`define  REG_RO2_BITS				31:0
`define  REG_RO2_WIDTH				32
`define  REG_RO2_DEFAULT				32'h0
`define  REG_RO2_ADDR				32'h18

`define  REG_RO3_BITS				31:0
`define  REG_RO3_WIDTH				32
`define  REG_RO3_DEFAULT				32'h0
`define  REG_RO3_ADDR				32'h1C

`define  REG_RO4_BITS				31:0
`define  REG_RO4_WIDTH				32
`define  REG_RO4_DEFAULT				32'h0
`define  REG_RO4_ADDR				32'h20

`define  REG_RO5_BITS				31:0
`define  REG_RO5_WIDTH				32
`define  REG_RO5_DEFAULT				32'h0
`define  REG_RO5_ADDR				32'h24

`define  REG_RO6_BITS				31:0
`define  REG_RO6_WIDTH				32
`define  REG_RO6_DEFAULT				32'h0
`define  REG_RO6_ADDR				32'h28

`define  REG_RO7_BITS				31:0
`define  REG_RO7_WIDTH				32
`define  REG_RO7_DEFAULT				32'h0
`define  REG_RO7_ADDR				32'h2C

`define  REG_RO8_BITS				31:0
`define  REG_RO8_WIDTH				32
`define  REG_RO8_DEFAULT				32'h0
`define  REG_RO8_ADDR				32'h30

`define  REG_RO9_BITS				31:0
`define  REG_RO9_WIDTH				32
`define  REG_RO9_DEFAULT				32'h0
`define  REG_RO9_ADDR				32'h34

`define  REG_RO10_BITS				31:0
`define  REG_RO10_WIDTH				32
`define  REG_RO10_DEFAULT				32'h0
`define  REG_RO10_ADDR				32'h38

`define  REG_RO11_BITS				31:0
`define  REG_RO11_WIDTH				32
`define  REG_RO11_DEFAULT				32'h0
`define  REG_RO11_ADDR				32'h3C

`define  REG_RO12_BITS				31:0
`define  REG_RO12_WIDTH				32
`define  REG_RO12_DEFAULT				32'h0
`define  REG_RO12_ADDR				32'h40

`define  REG_RO13_BITS				31:0
`define  REG_RO13_WIDTH				32
`define  REG_RO13_DEFAULT				32'h0
`define  REG_RO13_ADDR				32'h44

`define  REG_RO14_BITS				31:0
`define  REG_RO14_WIDTH				32
`define  REG_RO14_DEFAULT				32'h0
`define  REG_RO14_ADDR				32'h48

`define  REG_RO15_BITS				31:0
`define  REG_RO15_WIDTH				32
`define  REG_RO15_DEFAULT				32'h0
`define  REG_RO15_ADDR				32'h4C

`define  REG_RO16_BITS				31:0
`define  REG_RO16_WIDTH				32
`define  REG_RO16_DEFAULT				32'h0
`define  REG_RO16_ADDR				32'h50

`define  REG_RO17_BITS				31:0
`define  REG_RO17_WIDTH				32
`define  REG_RO17_DEFAULT				32'h0
`define  REG_RO17_ADDR				32'h54

`define  REG_RO18_BITS				31:0
`define  REG_RO18_WIDTH				32
`define  REG_RO18_DEFAULT				32'h0
`define  REG_RO18_ADDR				32'h58

`define  REG_RO19_BITS				31:0
`define  REG_RO19_WIDTH				32
`define  REG_RO19_DEFAULT				32'h0
`define  REG_RO19_ADDR				32'h5C

`define  REG_RO20_BITS				31:0
`define  REG_RO20_WIDTH				32
`define  REG_RO20_DEFAULT				32'h0
`define  REG_RO20_ADDR				32'h60

`define  REG_RO21_BITS				31:0
`define  REG_RO21_WIDTH				32
`define  REG_RO21_DEFAULT				32'h0
`define  REG_RO21_ADDR				32'h64

`define  REG_RO22_BITS				31:0
`define  REG_RO22_WIDTH				32
`define  REG_RO22_DEFAULT				32'h0
`define  REG_RO22_ADDR				32'h68

`define  REG_RO23_BITS				31:0
`define  REG_RO23_WIDTH				32
`define  REG_RO23_DEFAULT				32'h0
`define  REG_RO23_ADDR				32'h6C

`define  REG_RO24_BITS				31:0
`define  REG_RO24_WIDTH				32
`define  REG_RO24_DEFAULT				32'h0
`define  REG_RO24_ADDR				32'h70

`define  REG_RO25_BITS				31:0
`define  REG_RO25_WIDTH				32
`define  REG_RO25_DEFAULT				32'h0
`define  REG_RO25_ADDR				32'h74

`define  REG_RO26_BITS				31:0
`define  REG_RO26_WIDTH				32
`define  REG_RO26_DEFAULT				32'h0
`define  REG_RO26_ADDR				32'h78

`define  REG_RO27_BITS				31:0
`define  REG_RO27_WIDTH				32
`define  REG_RO27_DEFAULT				32'h0
`define  REG_RO27_ADDR				32'h7C

`define  REG_INDIRECTADDRESS_BITS				31:0
`define  REG_INDIRECTADDRESS_WIDTH				32
`define  REG_INDIRECTADDRESS_DEFAULT				32'h0
`define  REG_INDIRECTADDRESS_ADDR				32'h3000

`define  REG_INDIRECTWRDATA_BITS				31:0
`define  REG_INDIRECTWRDATA_WIDTH				32
`define  REG_INDIRECTWRDATA_DEFAULT				32'h0
`define  REG_INDIRECTWRDATA_ADDR				32'h3004

`define  REG_INDIRECTREPLY_BITS				31:0
`define  REG_INDIRECTREPLY_WIDTH				32
`define  REG_INDIRECTREPLY_DEFAULT				32'h0
`define  REG_INDIRECTREPLY_ADDR				32'h3008

`define  REG_INDIRECTCOMMAND_BITS				31:0
`define  REG_INDIRECTCOMMAND_WIDTH				32
`define  REG_INDIRECTCOMMAND_DEFAULT				32'h0
`define  REG_INDIRECTCOMMAND_ADDR				32'h300C

`define  REG_INDIRECTCONFIG_BITS				31:0
`define  REG_INDIRECTCONFIG_WIDTH				32
`define  REG_INDIRECTCONFIG_DEFAULT				32'h0
`define  REG_INDIRECTCONFIG_ADDR				32'h3010

`define  MEM_BARTABLE_DATA_BITS				31:0
`define  MEM_BARTABLE_ADDR_BITS				9:0
`define  MEM_BARTABLE_WIDTH				32
`define  MEM_BARTABLE_DEPTH				1024
`define  MEM_BARTABLE_ADDR				32'h0
